# Site settings
title: Leonardo Merlin
description: "A craftsman developer who lives in Brazil and work for the largest south american government company."
baseurl: ""
url: "http://leonardomerlin.com.br/"

name: Leonardo Merlin
email: hi@leonardomerlin.com.br
twitter_username: leonardomerlin
github_username:  leonardomerlin
google_analytics: UA-35971148-1

# Build settings
safe: false
source: ./src
destination: ./dist
paginate_path: 'blog/page:num'
plugins: ./src/_plugins

markdown: kramdown
highlighter: pygments
# permalink: /:title/
permalink: pretty
paginate: 5

exclued: ["node_modules"]
