
# Site settings
baseurl: ""

name: Leonardo Merlin
description: "A craftsman developer who lives in Brazil and work for the largest south american government company."
url: "http://leonardomerlin.com.br"
domain: "leonardomerlin.com.br"

email: hi@leonardomerlin.com.br
twitter_username: leonardomerlin
github_username:  leonardomerlin
google_analytics: UA-35971148-1

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/
paginate: 5